version: 0.1.{build}
before_build:
- cmd: nuget restore Corund 
nuget:
  disable_publish_on_pr: true
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package