version: 0.1.{build}
before_build:
- cmd: nuget restore Corund 
nuget:
  disable_publish_on_pr: true
build:
  publish_nuget: true
  verbosity: minimal
artifacts:
- path: '**\Corund*.nupkg'
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.1.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"